notifications:
  email: false
  irc:
    channels:
      - "irc.mysociety.org#sayit"
    use_notice: true

language: python

python:
  - "2.7"
  - "3.3"

services:
  - elasticsearch

env:
  - MODULES="Django>=1.4.2,<1.5 django-tastypie==0.9.16"
  - MODULES="Django>=1.6,<1.7 django-tastypie"
  - MODULES="Django>=1.7,<1.8 django-tastypie"
  - MODULES="git+https://github.com/django/django.git@master#egg=django django-tastypie"

# Django 1.4 did not support Python 3.
matrix:
  exclude:
    - python: "3.3"
      env: MODULES="Django>=1.4.2,<1.5 django-tastypie==0.9.16"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg libavcodec-extra-53 iceweasel xvfb
  - pip install $MODULES
  - CFLAGS="-O0" pip install -e .[test]

before_script:
  - psql -c 'create database "sayit-example-project";' -U postgres
  - ./manage.py syncdb --noinput
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - SELENIUM_TESTS=1 ./manage.py test
